package com.example.webviewurl

import android.annotation.SuppressLint
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.view.DragEvent
import android.webkit.WebView

class MainActivity : AppCompatActivity() {

    lateinit var webView: WebView

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        webView = findViewById(R.id.webview)

//        webView.loadUrl("https://webchat.7moor.com/wapchat.html?accessId=a902b190-fc75-11e9-9bd8-bd299448ef2d&fromUrl=2&urlTitle=1")


        webView.apply {
            loadData(
                "PCFET0NUWVBFIGh0bWw+PGh0bWw+PGhlYWQ+PG1ldGEgY2hhcnNldD0idXRmLTgiPjxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wIiAvPjwvaGVhZD48Ym9keT48ZGl2IGlkPSJjaGFydCI+PC9kaXY+PHNjcmlwdCBzcmM9Imh0dHBzOi8vY29kZS5oaWdoY2hhcnRzLmNvbS9oaWdoY2hhcnRzLmpzIj48L3NjcmlwdD48c2NyaXB0IHNyYz0iaHR0cHM6Ly9jb2RlLmhpZ2hjaGFydHMuY29tL21vZHVsZXMvbmV0d29ya2dyYXBoLmpzIj48L3NjcmlwdD4KPHNjcmlwdD4KICAgIEhpZ2hjaGFydHMuY2hhcnQoJ2NoYXJ0JywKICAgICAgICB7CiAgICAgICAgICAgIGNoYXJ0OiB7CiAgICAgICAgICAgICAgICB0eXBlOiAnbmV0d29ya2dyYXBoJywKICAgICAgICAgICAgICAgIGhlaWdodDogJzEwMCUnCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHRpdGxlOiB7CiAgICAgICAgICAgICAgICB0ZXh0OiAnVGhlIEluZG8tRXVyb3BlYW4gTGFuZ3VhZ2UgVHJlZScKICAgICAgICAgICAgfSwKICAgICAgICAgICAgc3VidGl0bGU6IHsKICAgICAgICAgICAgICAgIHRleHQ6ICdBIEZvcmNlLURpcmVjdGVkIE5ldHdvcmsgR3JhcGggaW4gSGlnaGNoYXJ0cycKICAgICAgICAgICAgfSwKICAgICAgICAgICAgcGxvdE9wdGlvbnM6IHsKICAgICAgICAgICAgICAgIG5ldHdvcmtncmFwaDogewogICAgICAgICAgICAgICAgICAgIGtleXM6IFsnZnJvbScsICd0byddLAogICAgICAgICAgICAgICAgICAgIGxheW91dEFsZ29yaXRobTogewogICAgICAgICAgICAgICAgICAgICAgICBlbmFibGVTaW11bGF0aW9uOiB0cnVlLAogICAgICAgICAgICAgICAgICAgICAgICBmcmljdGlvbjogLTAuOSwKICAgICAgICAgICAgICAgICAgICAgICAgbWF4SXRlcmF0aW9uczogNjAsCiAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9LAogICAgICAgICAgICBzZXJpZXM6IFt7CiAgICAgICAgICAgICAgICBkYXRhTGFiZWxzOiB7CiAgICAgICAgICAgICAgICAgICAgZW5hYmxlZDogZmFsc2UsCiAgICAgICAgICAgICAgICAgICAgbGlua0Zvcm1hdDogJycKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICBpZDogJ2xhbmctdHJlZScsCiAgICAgICAgICAgICAgICBkYXRhOiBbCiAgICAgICAgICAgICAgICAgICAgWydQcm90byBJbmRvLUV1cm9wZWFuJywgJ0JhbHRvLVNsYXZpYyddLAogICAgICAgICAgICAgICAgICAgIFsnUHJvdG8gSW5kby1FdXJvcGVhbicsICdHZXJtYW5pYyddLAogICAgICAgICAgICAgICAgICAgIFsnUHJvdG8gSW5kby1FdXJvcGVhbicsICdDZWx0aWMnXSwKICAgICAgICAgICAgICAgICAgICBbJ1Byb3RvIEluZG8tRXVyb3BlYW4nLCAnSXRhbGljJ10sCiAgICAgICAgICAgICAgICAgICAgWydQcm90byBJbmRvLUV1cm9wZWFuJywgJ0hlbGxlbmljJ10sCiAgICAgICAgICAgICAgICAgICAgWydQcm90byBJbmRvLUV1cm9wZWFuJywgJ0FuYXRvbGlhbiddLAogICAgICAgICAgICAgICAgICAgIFsnUHJvdG8gSW5kby1FdXJvcGVhbicsICdJbmRvLUlyYW5pYW4nXSwKICAgICAgICAgICAgICAgICAgICBbJ1Byb3RvIEluZG8tRXVyb3BlYW4nLCAnVG9jaGFyaWFuJ10sCiAgICAgICAgICAgICAgICAgICAgWydJbmRvLUlyYW5pYW4nLCAnRGFyZGljJ10sCiAgICAgICAgICAgICAgICAgICAgWydJbmRvLUlyYW5pYW4nLCAnSW5kaWMnXSwKICAgICAgICAgICAgICAgICAgICBbJ0luZG8tSXJhbmlhbicsICdJcmFuaWFuJ10sCiAgICAgICAgICAgICAgICAgICAgWydJcmFuaWFuJywgJ09sZCBQZXJzaWFuJ10sCiAgICAgICAgICAgICAgICAgICAgWydPbGQgUGVyc2lhbicsICdNaWRkbGUgUGVyc2lhbiddLAogICAgICAgICAgICAgICAgICAgIFsnSW5kaWMnLCAnU2Fuc2tyaXQnXSwKICAgICAgICAgICAgICAgICAgICBbJ0l0YWxpYycsICdPc2NvLVVtYnJpYW4nXSwKICAgICAgICAgICAgICAgICAgICBbJ0l0YWxpYycsICdMYXRpbm8tRmFsaXNjYW4nXSwKICAgICAgICAgICAgICAgICAgICBbJ0xhdGluby1GYWxpc2NhbicsICdMYXRpbiddLAogICAgICAgICAgICAgICAgICAgIFsnQ2VsdGljJywgJ0JyeXRob25pYyddLAogICAgICAgICAgICAgICAgXQogICAgICAgICAgICB9XQogICAgICAgIH0KICAgICk7Cjwvc2NyaXB0PjwvYm9keT48L2h0bWw+",
                "text/html; charset=utf-8",
                "base64"
            )

            settings.javaScriptEnabled = true
        }

    }


}